export const data = [
{"id":1,"vehiculo":"Cadillac","patente":"YCBE","duenos":"Flo Foulser","color":"Yellow","ano":1994,"marca":"Eldorado"},
{"id":2,"vehiculo":"Jaguar","patente":"SANR","duenos":"Sidney Wones","color":"Pink","ano":2000,"marca":"XK Series"},
{"id":3,"vehiculo":"Toyota","patente":"RPUB","duenos":"Talya McSporon","color":"Turquoise","ano":2000,"marca":"Avalon"},
{"id":4,"vehiculo":"Audi","patente":"RPMD","duenos":"Augusto Whitear","color":"Pink","ano":2009,"marca":"A3"},
{"id":5,"vehiculo":"Mercedes-Benz","patente":"KCMI","duenos":"Tilly Gorling","color":"Puce","ano":1992,"marca":"300SL"},
{"id":6,"vehiculo":"Suzuki","patente":"FKKW","duenos":"Rozalin Dymick","color":"Khaki","ano":2003,"marca":"XL-7"},
{"id":7,"vehiculo":"Chevrolet","patente":"KCTY","duenos":"Sutherlan Hadlington","color":"Orange","ano":2006,"marca":"Uplander"},
{"id":8,"vehiculo":"Mitsubishi","patente":"RCLY","duenos":"Janis Drees","color":"Orange","ano":1999,"marca":"Pajero"},
{"id":9,"vehiculo":"Volvo","patente":"LIDB","duenos":"Dorine Pellamont","color":"Khaki","ano":2005,"marca":"V70"},
{"id":10,"vehiculo":"Mercedes-Benz","patente":"NVSQ","duenos":"Keene Deeson","color":"Goldenrod","ano":1993,"marca":"500SL"},
{"id":11,"vehiculo":"Chevrolet","patente":"KHUT","duenos":"Garik Laughrey","color":"Purple","ano":2004,"marca":"Cavalier"},
{"id":12,"vehiculo":"Ford","patente":"KABR","duenos":"Olag Grammer","color":"Green","ano":1996,"marca":"F250"},
{"id":13,"vehiculo":"Rolls-Royce","patente":"HKMA","duenos":"Clara M'Barron","color":"Green","ano":2008,"marca":"Phantom"},
{"id":14,"vehiculo":"Scion","patente":"MMZO","duenos":"Bonita Hryniewicz","color":"Indigo","ano":2006,"marca":"xA"},
{"id":15,"vehiculo":"Ford","patente":"LCPH","duenos":"Jamesy Yve","color":"Crimson","ano":2001,"marca":"F250"},
{"id":16,"vehiculo":"Audi","patente":"KTOA","duenos":"Alleyn Firebrace","color":"Goldenrod","ano":2008,"marca":"Q7"},
{"id":17,"vehiculo":"Ford","patente":"YMVG","duenos":"Grazia Po","color":"Puce","ano":2013,"marca":"Mustang"},
{"id":18,"vehiculo":"Toyota","patente":"RPVM","duenos":"Rickie Boulger","color":"Aquamarine","ano":2012,"marca":"Prius Plug-in Hybrid"},
{"id":19,"vehiculo":"GMC","patente":"OIKY","duenos":"Omar Haddinton","color":"Mauv","ano":2000,"marca":"Sierra 1500"},
{"id":20,"vehiculo":"Volkswagen","patente":"EISG","duenos":"Orelie Wicher","color":"Violet","ano":1997,"marca":"rio"}];